#
# Default variables
#

ansible_master: 'root@localhost'

admins: Null
admins_emails:
  - 'root@localhost'

locale: 'en_US.UTF-8'
timezone_area: 'Europe'
timezone_city: 'Paris'

with_hosts: False
with_hostsdeny: False
hosts_fqdn: True
hosts_static_lookup: Null

ipv6_disabled: False

debian_mirror: 'http://httpredir.debian.org/debian'

apt_keys: Null
apt_repositories: Null
apt_additional_packages: Null

hosts_deny_nfs: False
host_deny_paranoid: False

with_auto_upgrade: False
auto_upgrade_additional_patterns: Null

with_logcheck: False
with_rkhunter: False
with_chkrootkit: False

with_hideproc: False
hideproc_gid: ''

with_ntp: True

with_firewall: False
firewall_debug: False
firewall_interface: Null
firewall_public:
  - 'ssh'
  - 'http'
  - 'https'
  - 'smtp'

with_smartd: False

with_postfix: False
with_postfix_slowsmtp: False
with_mail_aliases: False
with_postfix_external_smtp: False
postfix_external_smtp_host_localdomain: Null
postfix_external_smtp_credentials: Null
postfix_external_smtp_relays: Null
postfix_external_sender_rewrites: Null

with_ssh: True
ssh_strengthened: True
ssh_ports:
  - 22
ssh_usedns: True
ssh_allowed_users: Null
ssh_allowed_groups:
  - 'root'
  - 'operator'
  - 'ssh'

with_dnscache: False

with_ovh: False

sysfs_disk_settings: False

with_dotfiles: False
dotfiles_repo: 'https://git.openics.org/kolter/dotfiles-sys.git'
dotfiles_dest: '/srv/hosting-tools/shell'
dotfiles_lcsshvars: 0

ssl_certs: Null
ssl_certs_auto: Null

dkim_domains: Null
with_opendkim: False

# vim: ft=yaml
