#
# Default variables
#

ansible_master: 'root@localhost'

admins: []
admins_emails:
  - 'root@localhost'
with_admins_accounts: True

locale: 'en_US.UTF-8'
timezone_area: 'Europe'
timezone_city: 'Paris'

with_hosts: False
with_hostsdeny: False
hosts_fqdn: True
hosts_static_lookup: []

ipv6_disabled: False

debian_mirror: 'https://deb.debian.org'

apt_keys: []
apt_repositories: []
apt_additional_packages: []
apt_additional_packages_local: []
with_apt_sources: False
with_apt_backports: False
with_base_packages: True

hosts_deny_nfs: False
host_deny_paranoid: False

with_auto_upgrade: False
auto_upgrade_additional_patterns: []

with_logcheck: False
with_rkhunter: False
with_chkrootkit: False

with_logrotate4rsyslog_override: True

with_hideproc: False
hideproc_gid: ''

with_sudo: True

with_dhparam: True

with_ntp: True

with_firewall: False
firewall_debug: False
firewall_interface: Null
firewall_public:
  - 'ssh'
  - 'http'
  - 'https'
  - 'smtp'

with_smartd: False

with_postfix: False
postfix_ssl_fortify: False
with_postfix_slowsmtp: False
with_mail_aliases: False
with_postfix_external_smtp: False
postfix_external_smtp_host_localdomain: Null
postfix_external_smtp_credentials: Null
postfix_external_smtp_relays: Null
postfix_external_sender_rewrites: Null

dkim_domains: []
dkim_selector: 'default'
with_opendkim: False

with_rspamd: False
with_rspamd_upstream: False
rspamd_composites: True
rspamd_actions: True
rspamd_actions_score_reject: 30
rspamd_actions_score_add_header: 6
rspamd_actions_score_greylist: 4
rspamd_actions_score_rewrite_subject: 8
rspamd_multimap: True
rspamd_multimap_prefix: ''
rspamd_external_relay: []
rspamd_rbl_group: True
rspamd_redis_history: True
rspamd_redis_history_nrows: 200
rspamd_surbl_group: True
rspamd_multimap_rules_body_spammy: []
rspamd_multimap_rules_headers_spammy: []
rspamd_multimap_whitelist_sender: []
rspamd_multimap_whitelist_sender_domain: []
rspamd_multimap_blacklist_sender: []
rspamd_multimap_blacklist_sender_domain: []
rspamd_multimap_score_whitelist_envfrom: -9.0
rspamd_multimap_score_whitelist_envfrom_domain: -9.0
rspamd_multimap_score_whitelist_from: -2.2
rspamd_multimap_score_whitelist_from_domain: -2.2
rspamd_multimap_score_blacklist_from: 20.0
rspamd_multimap_score_blacklist_from_domain: 20.0
rspamd_multimap_score_spammy_body: 1.0
rspamd_multimap_score_check_headers: 1.0
rspamd_whitelist: True
rspamd_whitelist_dmarc: []
rspamd_whitelist_spfdkim: []
rspamd_metrics: {}
rspamd_regexp: True
rspamd_milter_headers: True

with_ssh: True
ssh_strengthened: True
ssh_ports:
  - 22
ssh_usedns: True
ssh_allowed_users: []
ssh_allowed_groups:
  - 'root'
  - 'operator'
  - '{% if ansible_lsb.major_release|int >= 12 %}_{% endif %}ssh'

with_dnscache: False

with_docker: False
with_docker_upstream: False

sysfs_disk_settings: False

with_dotfiles: False
dotfiles_repo: 'https://git.openics.org/kolter/dotfiles-sys.git'
dotfiles_dest: '/srv/hosting-tools/shell'
dotfiles_lcsshvars: 0

ssl_certs: []
ssl_certs_auto: []

with_geoip: False
geoip_accountid: Null
geoip_licencekey: Null
geoip_editionids: []
