#!/bin/sh

# {{{ Variables
APT_OPTS="-qq --yes --no-install-recommends -o 'Apt::Cmd::Disable-Script-Warning=true' -o 'Dpkg::Use-Pty=0'"
# }}}

# {{{ bootstrap_grub
bootstrap_grub() {
    echo "[INFO] Creating grub configuration (${HYPERVISOR})"

    if [ "${HYPERVISOR}" = "xen-pvm" ] || [ "${HYPERVISOR}" = "xen-hvm" ]; then
        mkdir -p "${TARGET}/boot/grub"

        # Create virtual disk in /dev
        mknod "${TARGET}/dev/xvda" b $(stat -L -c "0x%t 0x%T" "${BLOCKDEV}")

        # Create virtual partition in /dev
        mknod "${TARGET}/dev/xvda1" b $(stat -L -c "0x%t 0x%T" "${FSYSDEV}")

        # Create grub device map
        echo "(hd0) /dev/xvda" > "${TARGET}/boot/grub/device.map"

        # Create grub.cfg
        chroot "${TARGET}" update-grub

        # Cleanup
        rm -f "${TARGET}/dev/xvda1" "${TARGET}/dev/xvda"
    else
        PACKAGES="grub-pc"
        export DEBIAN_FRONTEND="noninteractive"
        chroot "${TARGET}" apt ${APT_OPTS} install ${PACKAGES}

        mkdir -p "${TARGET}/dev" "${TARGET}/boot/grub"

        if [ -e "${DISK_0_PATH}" ]; then
            for mp in /dev /proc ; do
                echo "[DEBUG] Bind mounting "${mp}" to ${TARGET}"
                mount --bind "${mp}" "${TARGET}${mp}"
            done

            if [ -f "${TARGET}/etc/default/grub" ]; then
                echo "[INFO] Adding kernel parameters in grub for serial console"
                sed -i -E 's/^(GRUB_CMDLINE_LINUX_DEFAULT=).*$/\1"console=ttyS0,115200n8 console=tty1 net.ifnames=0"/' \
                    "${TARGET}/etc/default/grub"

                echo "[INFO] Updating grub configuration"
                chroot "${TARGET}" update-grub
            fi

            echo "[INFO] Installing grub on ${DISK_0_PATH}"
            chroot "${TARGET}" grub-install --recheck "${DISK_0_PATH}"

            for mp in /dev /proc ; do
                echo "[DEBUG] Bind unmounting "${mp}" to ${TARGET}"
                umount "${TARGET}${mp}"
            done
        fi
    fi
}
# }}}

# {{{ main
if [ -z "${TARGET}" -o ! -d "${TARGET}" ]; then
    echo "[ERR] Instance bootstrap hook: missing target directory"
    exit 1
fi

if [ "$(mountpoint -d /)" = "$(mountpoint -d "${TARGET}")" ]; then
    echo "[ERR] The target directory seems to be the root dir, aborting." 1>&2
    exit 1
fi

bootstrap_grub

exit 0
# }}}

# vim: foldmethod=marker foldlevel=0 foldenable
