#
# Default variables for webservers
#

with_apache2: False
with_apache2_modphp5: False

with_nginx: False
# nginx_workers ~= $(getconf _NPROCESSORS_ONLN)
nginx_workers: 2

with_fpm: False
fpm_pool_count: 1
fpm_user: 'www-data'
fpm_group: 'www-data'
# fpm_max_children ~= (total RAM - RAM used by other process) / (average amount of RAM used by a PHP process)
fpm_start_servers: 2
fpm_max_children: 5
fpm_min_spare_servers: 1
fpm_max_spare_servers: 3

with_php: False
with_php_lt_54: False
phpsyscheck_vhostname: sys.localhost
php_config:
  - key: 'date.timezone'
    value: 'Europe/Paris'
  - key: 'short_open_tag'
    value: 'off'
  - key: 'expose_php'
    value: 'off'

php_config_web:
  - key: 'display_errors'
    value : 'off'
  - key: 'display_startup_errors'
    value: 'off'
  - key: 'log_errors'
    value: 'on'
  - key: 'html_errors'
    value: 'off'
  - key: 'cgi.fix_pathinfo'
    value: '0'
# Set with /etc/default/php5-fpm (see https://bugs.php.net/bug.php?id=66239)
#  - key: 'error_log'
#    value: 'syslog'

with_php_apc: False

with_phpmyadmin: False
phpmyadmin_vhostname: pma.localhost

http_auth_admin_password: seVDetGvSs7nA # openssl passwd -crypt adm123in

# vim: ft=yaml
