#
# Default variables for webservers
#

http_ssl_strengthened: False

with_apache2: False

with_nginx: False
nginx_workers: 'auto'
nginx_http_config: Null
nginx_security_xframeoptions: True
nginx_security_xxssprotection: True
nginx_security_xcontenttypeoptions: True
nginx_fpm_openbasedir_enforced: False

with_modphp5: False
with_modphp: False

with_fpm: False

fpm_pool_count: 1
fpm_user: 'www-data'
fpm_group: 'www-data'
# fpm_max_children ~= (total RAM - RAM used by other process) / (average amount of RAM used by a PHP process)
fpm_pm: 'dynamic'
fpm_start_servers: 2
fpm_max_children: 5
fpm_min_spare_servers: 1
fpm_max_spare_servers: 3

fpm_pools: Null

with_php: False
php_version: '7.0'
with_php_mysql_legacy: False

with_phpsyscheck: True
phpsyscheck_vhostname: 'sys.localhost'
phpsyscheck_vhostip: Null
phpsyscheck_vhostport: Null
phpsyscheck_ssl: False
phpsyscheck_http_auth: False
phpsyscheck_http_whitelist_ip: []

php_config:
  date.timezone: 'Europe/Paris'
  short_open_tag: 'off'
  expose_php: 'off'

php_config_web:
  display_errors: 'off'
  display_startup_errors: 'off'
  log_errors: 'on'
  html_errors: 'off'
  session.cookie_secure: 'on'
# Set with /etc/default/php5-fpm (see https://bugs.php.net/bug.php?id=66239)
#  error_log: 'syslog'

with_php_apc: False

with_phpmyadmin: False
phpmyadmin_vhostname: 'pma.localhost'
phpmyadmin_vhostip: Null
phpmyadmin_vhostport: Null
phpmyadmin_ssl: False
phpmyadmin_http_auth: False
phpmyadmin_http_whitelist_ip: []

with_phppgadmin: False
phppgadmin_vhostname: 'pga.localhost'
phppgadmin_vhostip: Null
phppgadmin_vhostport: 80
phppgadmin_http_auth: False
phppgadmin_http_whitelist_ip: []

http_auth_admin_password: Null
http_auth_user_name: Null
http_auth_user_password: Null

# vim: ft=yaml.ansible
