#
# Default variables for webservers
#

http_ssl_strengthened: False

with_apache2: False

with_nginx: False
nginx_workers: 'auto'
nginx_http_config: []
nginx_security_xframeoptions: True
nginx_security_xxssprotection: True
nginx_security_xcontenttypeoptions: True
nginx_fpm_openbasedir_enforced: False
nginx_logfmt_json: False
with_nginx_sury: False

with_modphp5: False
with_modphp: False

with_fpm: False
with_fpm_config: True

fpm_pool_name: 'www'
fpm_pool_count: 1
fpm_user: 'www-data'
fpm_group: 'www-data'
# fpm_max_children ~= (total RAM - RAM used by other process) / (average amount of RAM used by a PHP process)
fpm_pm: 'dynamic'
fpm_start_servers: 2
fpm_max_children: 5
fpm_min_spare_servers: 1
fpm_max_spare_servers: 3
fpm_process_idle_timeout: 10

fpm_pools: []
fpm_pools_include_pattern: 'local-pool.cnf'

with_php: False
php_version: '7.0'
with_php_mysql_legacy: False
with_php_sury: False

with_phpsyscheck: True
phpsyscheck_vhostname: 'sys.localhost'
phpsyscheck_vhostip: ''
phpsyscheck_vhostport: 0
phpsyscheck_ssl: False
phpsyscheck_http_auth: False
phpsyscheck_http_whitelist_ip: []
phpsyscheck_apache2_enabled: True
phpsyscheck_nginx_enabled: True

with_selfvhost: True
selfvhost_vhostname: 'localhost'
selfvhost_vhostip: ''
selfvhost_vhostport: 0
selfvhost_ssl: False
selfvhost_apache2_enabled: True
selfvhost_nginx_enabled: True

php_config:
  date.timezone: 'Europe/Paris'
  short_open_tag: 'off'
  expose_php: 'off'

php_config_web:
  display_errors: 'off'
  display_startup_errors: 'off'
  log_errors: 'on'
  html_errors: 'off'
  session.cookie_secure: 'on'
# Set with /etc/default/php5-fpm (see https://bugs.php.net/bug.php?id=66239)
#  error_log: 'syslog'

with_php_apc: False

with_phpmyadmin: False
phpmyadmin_rootdir: '/usr/share/phpmyadmin'
phpmyadmin_vhostname: 'pma.localhost'
phpmyadmin_vhostip: ''
phpmyadmin_vhostport: 0
phpmyadmin_ssl: False
phpmyadmin_http_auth: False
phpmyadmin_http_whitelist_ip: []
phpmyadmin_apache2_enabled: True
phpmyadmin_nginx_enabled: True

with_phppgadmin: False
phppgadmin_vhostname: 'pga.localhost'
phppgadmin_vhostip: ''
phppgadmin_vhostport: 0
phppgadmin_http_auth: False
phppgadmin_http_whitelist_ip: []

http_auth_admin_password: ''
http_auth_user_name: ''
http_auth_user_password: ''

# vim: ft=yaml.ansible
