#
# Default variables for webservers
#

with_apache2: False

with_nginx: False
# nginx_workers ~= $(getconf _NPROCESSORS_ONLN)
nginx_workers: 2
nginx_ssl_strengthened: False

with_modphp5: False

with_fpm: False
fpm_pool_count: 1
fpm_user: 'www-data'
fpm_group: 'www-data'
# fpm_max_children ~= (total RAM - RAM used by other process) / (average amount of RAM used by a PHP process)
fpm_start_servers: 2
fpm_max_children: 5
fpm_min_spare_servers: 1
fpm_max_spare_servers: 3

with_php: False
with_php_mysql_legacy: False

phpsyscheck_vhostname: 'sys.localhost'

php_config:
  date.timezone: 'Europe/Paris'
  short_open_tag: 'off'
  expose_php: 'off'

php_config_web:
  display_errors: 'off'
  display_startup_errors: 'off'
  log_errors: 'on'
  html_errors: 'off'
# Set with /etc/default/php5-fpm (see https://bugs.php.net/bug.php?id=66239)
#  error_log: 'syslog'

with_php_apc: False

with_phpmyadmin: False
phpmyadmin_vhostname: 'pma.localhost'
http_auth_phpmyadmin: False

with_phppgadmin: False
phppgadmin_vhostname: 'pga.localhost'
http_auth_phppgadmin: False

http_auth_admin_password: Null
http_auth_user_name: Null
http_auth_user_password: Null

# vim: ft=yaml
