- name: 'Install dotfiles'
  git:
    repo: '{{ dotfiles_repo }}'
    dest: '{{ dotfiles_dest }}'
    recursive: 'yes'
    accept_hostkey: 'yes'
    force: 'yes'
  tags:
    - 'base'
    - 'dotfiles'

- name: 'Enable sourcing of dotfiles'
  lineinfile:
    dest: '/etc/zsh/zshrc'
    regexp: 'source {{ dotfiles_dest }}'
    line: '[[ -f {{ dotfiles_dest }}/zsh/zshrc ]] && export LC_SSH_VARS={{ dotfiles_lcsshvars }} && source {{ dotfiles_dest }}/zsh/zshrc'
  tags:
    - 'base'
    - 'dotfiles'

# vim: ft=yaml.ansible
