- name: Install apache2 packages
  apt: pkg=apache2 state=installed update_cache=yes
  when: with_apache2

- name: Install apache2 basic security configuration (Debian < 8)
  template: src=apache2/conf.d/security.j2 dest=/etc/apache2/conf.d/security owner=root group=root mode=0644
  notify:
    - Reload apache2
  when: with_apache2 and ansible_lsb.major_release|int < 8

- name: Install apache2 basic security configuration (Debian >= 8)
  template: src=apache2/conf.d/security.j2 dest=/etc/apache2/conf-available/security.conf owner=root group=root mode=0644
  notify:
    - Reload apache2
  when: with_apache2 and ansible_lsb.major_release|int >= 8

- name: Create basic authentication file for admin (apache2)
  template: src=apache2/auth_admin.j2 dest=/etc/apache2/auth_admin owner=root group=www-data mode=0640
  when: with_apache2

- name: Install PHPMyAdmin virtual host for apache2 (sites-available)
  template: src=apache2/pma_vhost.j2 dest=/etc/apache2/sites-available/pma.conf owner=root group=root mode=0644
  notify:
    - Reload apache2
  when: with_phpmyadmin and with_apache2

- name: Install PHPMyAdmin virtual host for apache2 (sites-enabled)
  file: src=/etc/apache2/sites-available/pma.conf path=/etc/apache2/sites-enabled/pma.conf state=link
  notify:
    - Reload apache2
  when: with_phpmyadmin and with_apache2

- name: Install PHP system checks virtual host for apache2 (sites-available)
  template: src=apache2/sys_vhost.j2 dest=/etc/apache2/sites-available/sys.conf owner=root group=root mode=0644
  notify:
    - Reload apache2
  when: with_php and with_apache2

- name: Install PHP system checks virtual host for apache2 (sites-enabled)
  file: src=/etc/apache2/sites-available/sys.conf path=/etc/apache2/sites-enabled/sys.conf state=link
  notify:
    - Reload apache2
  when: with_php and with_apache2

- name: Ensure apache2 is running
  service: name=apache2 state=started
  when: with_apache2
