#
# Default variables for webservers
#

with_mysql: False
with_mariadb: False
with_mysql_backup: True
mysql_root_password: ''
mysql_admin_password: ''

with_postgresql: False
with_postgresql_backup: True

# vim: ft=yaml
